version: '2'

services:
  base:
    image: node:12
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - ./app/server:/usr/src/app/
    working_dir: /usr/src/app/
  install:
    extends:
      service: base
    command: npm i

volumes:
  nodemodules:
    external: true
